<?php declare(strict_types = 1);

namespace Adbros\Exam\Model;

/**
 * Do not edit this file!
 */
interface Repository
{

	/**
	 * @return array<Entity>
	 */
	public function findAll(): array;

	public function getByEmail(string $email): ?Entity;

	public function persist(Entity $userEntity): Entity;

}
