<?php declare(strict_types = 1);

namespace Adbros\Exam\Model\User;

use Adbros\Exam\Model\Entity;
use Adbros\Exam\Model\Repository;

/**
 * Do not edit this file!
 */
final class UserRepository implements Repository
{

	/** @var UserEntity[] */
	private array $data = [];

	/**
	 * @return UserEntity[]
	 */
	public function findAll(): array
	{
		return array_values($this->data);
	}

	public function getByEmail(string $email): ?UserEntity
	{
		return $this->data[$email] ?? null;
	}

	/**
	 * @param Entity|UserEntity $userEntity
	 */
	public function persist(Entity $userEntity): UserEntity
	{
		$this->data[$userEntity->getEmail()] = $userEntity;

		return $userEntity;
	}

}
